return {
	test_office = { time = 360, rounds = 6, dark = true },
	test_homestead = { time = 240, rounds = 6, dark = false },
	test_crossroad = { time = 360, rounds = 6, dark = true },
	test_complex_night = { time = 240, rounds = 6, dark = false },
	shipment = { time = 480, rounds = 6, dark = true },
	sandstorm7v7 = { time = 360, rounds = 6, dark = true },
	nabolag = { time = 360, rounds = 6, dark = true },
	misc_backrooms = { time = 180, rounds = 2, dark = true },
	delivery = { time = 360, rounds = 6, dark = true },
	test_nuristan = { time = 480, rounds = 2, dark = true },
};
